const reports = [
  {
    id: 1,
    bug: "Proxy unable to connect to remote server",
    reporter: {
      firstName: "Shaun",
      lastName: "Pelling",
    },
    status: "OPEN",
    severity: "MINOR",
    created: "1597968000000",
    updated: "1597968000000",
    project: "Trancate",
  },
  {
    id: 2,
    bug: "Code could not be commited to remote repo",
    reporter: {
      firstName: "Shaun",
      lastName: "Pelling",
    },
    status: "IN PROGRESS",
    severity: "MODERATE",
    created: "1597968000000",
    updated: "1597968000000",
    project: "Buggy",
  },
  {
    id: 3,
    bug: "Remote API endpoints not responding",
    reporter: {
      firstName: "Shaun",
      lastName: "Pelling",
    },
    status: "TO BE TESTED",
    severity: "MAJOR",
    created: "1597968000000",
    updated: "1597968000000",
    project: "Buggy",
  },
  {
    id: 4,
    bug: "App crashes after second loading",
    reporter: {
      firstName: "Shaun",
      lastName: "Pelling",
    },
    status: "CLOSED",
    severity: "CRITICAL",
    created: "1597968000000",
    updated: "1597968000000",
    project: "Trancate",
  },
  {
    id: 5,
    bug: "App crashes after second loading",
    reporter: {
      firstName: "Shaun",
      lastName: "Pelling",
    },
    status: "CLOSED",
    severity: "CRITICAL",
    created: "1597968000000",
    updated: "1597968000000",
    project: "Trancate",
  },
  {
    id: 6,
    bug: "App crashes after second loading",
    reporter: {
      firstName: "Shaun",
      lastName: "Pelling",
    },
    status: "CLOSED",
    severity: "CRITICAL",
    created: "1597968000000",
    updated: "1597968000000",
    project: "Trancate",
  },
  {
    id: 7,
    bug: "App crashes after second loading",
    reporter: {
      firstName: "Shaun",
      lastName: "Pelling",
    },
    status: "CLOSED",
    severity: "CRITICAL",
    created: "1597968000000",
    updated: "1597968000000",
    project: "Trancate",
  },
  {
    id: 8,
    bug: "App crashes after second loading",
    reporter: {
      firstName: "Shaun",
      lastName: "Pelling",
    },
    status: "CLOSED",
    severity: "CRITICAL",
    created: "1597968000000",
    updated: "1597968000000",
    project: "Trancate",
  },
  {
    id: 9,
    bug: "App crashes after second loading",
    reporter: {
      firstName: "Shaun",
      lastName: "Pelling",
    },
    status: "CLOSED",
    severity: "CRITICAL",
    created: "1597968000000",
    updated: "1597968000000",
    project: "Trancate",
  },
  {
    id: 10,
    bug: "App crashes after second loading",
    reporter: {
      firstName: "Shaun",
      lastName: "Pelling",
    },
    status: "CLOSED",
    severity: "CRITICAL",
    created: "1597968000000",
    updated: "1597968000000",
    project: "Trancate",
  },
  {
    id: 11,
    bug: "App crashes after second loading",
    reporter: {
      firstName: "Shaun",
      lastName: "Pelling",
    },
    status: "CLOSED",
    severity: "CRITICAL",
    created: "1597968000000",
    updated: "1597968000000",
    project: "Trancate",
  },
];

export default reports;
